export const TIPS = {
  OH:       'Operating hours per year. A 24/7 facility = 8,760 hrs; typical office = ~2,500 hrs; hospitality ~4,000–5,000 hrs. Drives annual energy and lifetime calculations.',
  PL:       'How long the installation is expected to remain in service before a full refresh. Affects how many replacement cycles occur and the total cost/carbon profile.',
  ER:       'Current electricity tariff in AUD per kWh. Affects the present value of all energy costs over the project life. Check your utility bill for the applicable rate.',
  GF_0:     'Current grid emission intensity in kg CO₂e per kWh. Australian average is ~0.39 kg/kWh (2024); varies by state. Source: DISR Quarterly Carbon Accounting.',
  GD:       'The percentage reduction in grid carbon intensity expected over the decarbonisation timeframe. E.g. 30% means the grid factor falls to 70% of its starting value.',
  GDT:      'The number of years over which the grid decarbonisation is assumed to occur linearly. After this point the grid factor is held at the floor value.',
  i:        'General inflation rate used to escalate future costs (energy and replacement) in nominal terms. RBA long-run target is 2.5%; use 3–4% for conservative planning.',
  d:        'The opportunity cost of capital — used to discount future cash flows to present value. This is separate from the loan interest rate. Typical range: 4–8% for commercial property.',
  W:        'Rated wattage of the luminaire (excluding drivers). Lower wattage at equivalent lumen output = better efficacy. Drives annual energy consumption.',
  FL:       'Initial lumen output per luminaire. Together with wattage, this determines efficacy (lm/W) — the primary comparative efficiency metric.',
  Q:        'The base design quantity — how many luminaires are needed to achieve target light levels at end of life. The tool adjusts this upward by 1/LMF to account for lumen depreciation.',
  LMF:      'Luminaire Maintenance Factor: the fraction of initial lumens retained at end of rated life. LMF = 0.9 (L90) means 10% depreciation; LMF = 0.7 (L70) means 30% depreciation. Lower LMF requires more luminaires installed (Q/LMF) to maintain minimum light levels at end of life.',
  LH:       'Manufacturer-rated hours to the LMF threshold. A 50,000 hr luminaire at 5,000 hrs/yr = 10-year lifetime. Longer LH means fewer replacement cycles over the project life.',
  GWP_CG:   'Embodied carbon from raw material extraction through manufacturing and delivery to site (cradle-to-gate). Source from EPDs (Environmental Product Declarations) where available.',
  GWP_EOL:  'Carbon associated with end-of-life processing — landfill, recycling transport, and disposal. Typically 5–15% of cradle-to-gate. Source EPDs or use default if unavailable.',
  C_SI:     'Combined supply and installation cost per luminaire including driver, lamp (if separate), labour, and any associated control gear. Excludes control system upgrades.',
  CSC:      'Control System Coefficient: the fraction of base energy consumed with controls active. CSC = 0.75 means a 25% energy reduction. Typical range: 0.55–0.80 depending on occupancy patterns, daylight availability, and task requirements.',
  CACC:     'Control Additional Cost Coefficient: the multiplier applied to the base supply+install cost to estimate the additional per-luminaire cost of the control system. CACC = 1.15 means 15% uplift.',
  r:        'The annual interest rate on the loan used to finance the control system upgrade. This is distinct from the project discount rate — they serve different purposes.',
  LT:       'The term over which the control system loan is repaid. Affects annual repayment size and total interest paid. Should match the financing agreement.',
};
